duckduckgo/duckduckgo

- lib/DDG/Meta/Helper.pm
Add boolean helpers for true and false.  This will be helpful for Goodie devs using Spice documentation for templates.
Could also be done locally for Goodies only in DDG::Goodie.  This change will add true/false for everyone, though there isn't a lot of Perl dev for the other IAs now.
> DDG::Meta::Helper: add boolean helpers

- CONTRIBUTING.md
- README.md
Removing dukgo links and updating rebasing guide. 
cc @moollaza
> Updating readme

- lib/DDG/Request.pm
- t/15-request.t
generate_triggers() has a few issues that should be fixed:
* Lines 190-2 and 193 are doing the same thing.
* Remove List::MoreUtils and refactor for efficiency (it's quite a bit faster.)
Note.
* The triggers are no longer sort'ed.  I didn't see where this made a difference but it's certainly possible I overlooked it.
> Fix bug in DDG::Request and refactor

- lib/DDG/Meta/ShareDir.pm
Fixes duckduckgo/p5-app-duckpan#229
Will need to check if this doesn’t break anything
> Removed case to set root by checking directory t

- .travis.yml
> update .travis.yml to match dist.ini specified perl versions

- lib/DDG/Meta/Data.pm
Catch encode_json failures with eval and warn.  Also clean up some whitespace issues.
> Tweak get_js

- lib/DDG/Meta/Data.pm
> remove newline

- lib/DDG/Meta/Data.pm
Adds `source_data` to access fathead specific metadata and a hash indexed by source id.
@zachthompson @russellholt
> fathead metadata

- lib/DDG/Meta/Data.pm
We don't really need to force read-only metadata.
> Remove clone'ing of metadata

- lib/DDG/Meta/Data.pm
I added a few more hash look up functions for fatheads.
> add by_source, by_lang, and by_length

- lib/DDG/Meta/Data.pm
Attempt to download metdata json files from https://duck.co on start before resorting to using previously downloaded json.
> Download metadata json files on start up

- lib/DDG/Rewrite.pm
- t/50-spice.t
- t/55-rewrite.t
Making a change to Rewrite.pm to use variables in generated.conf for proxy_pass
@nilnilnil @zachthompson @tommytommytommy
> use variables in proxy_pass for dynamic nginx resolution

- lib/DDG/Meta/Data.pm
* Use new all/json endpoint so we don't need to make requests by IA type
* Request compressed response to reduce bandwidth
cc @jbarrett @jkv
> Update metadata download

- lib/DDG/Meta/Data.pm
* Add and environment variable - `METADATA_TMP_DIR` -` to specify different metadata tmp directories
* Default to `/var/tmp`
cc @jkv
> Add ENV var for metadata download location

- lib/DDG/Meta/Data.pm
Request compressed metadata json from duck.co endpoint.   Still handles text/html responses.  Will need to be test on a server where json is being gzipped (ping @jkv).
> Request compressed metadata json

- lib/DDG/Meta/Data.pm
* Retrieve metadata from S3
* Remove support for uncompressed files.
* Switch to bzip2
> Get metadata from S3

- lib/DDG/Meta/ZeroClickInfoSpice.pm
- lib/DDG/Rewrite.pm
Modify Rewrite.pm to return custom json in the case of an upstream error. Needs coordination with https://github.com/duckduckgo/zeroclickinfo-spice/pull/2267
> Adding fallback for 404's

- lib/DDG/Meta/Data.pm
> Remove IsAwesome exceptions

- lib/DDG/Rewrite.pm
- t/50-spice.t
- t/55-rewrite.t
This was introduced in #71 but I think it should be universally applied.
> Unconditionally include proxy header config

- lib/DDG/Meta/Data.pm
Make a temporary backup of existing metadata before mirroring.  Restore and use it if a newly downloaded file fails.
> Metadata: Temp backup of existing file

- lib/DDG/Meta/ZeroClickInfoSpice.pm
- lib/DDG/Rewrite.pm
- t/55-rewrite.t
> Add new content_type_js attribute to force content-type
