- lib/DDG/Block/Words.pm
- t/50-spice.t
- t/lib/DDGTest/Spice/MultiTriggerType.pm
//cc @yegg @nilnilnil @russellholt 
While @yegg and I were trying to solve a potential triggering problem, we began refactoring a small portion of `Words.pm`. 
The triple ternary used to check for trigger matches has been simplified and now allows a fallback check against other trigger types that also matches against the current word. Therefore if an IA has both a `start` and `any` trigger that match against the current word, if the `start` trigger fails to match, the `any` trigger still has an opportunity to match. Before, only the first type of trigger that partially matched was checked and upon failure, the next word was considered.
Most of this fix was written by @yegg, I've provided the comments.
> Words.pm - Simplified Words Triggering

- lib/DDG.pm
/cc @russellholt @jagtalon @jbarrett 
This will create the same problems DuckPAN face and isn't needed with the changes to DuckPAN: https://github.com/duckduckgo/p5-app-duckpan/pull/209
Only devs actively working on this repo should ever be running the DDG code "in-place" so this shouldn't affect anyone.
> Allow PkgVersion to set the version, DuckPAN will default to 9.999 if  isn't defined

- dist.ini
- lib/DDG/Meta.pm
- lib/DDG/Meta/CountryCodes.pm
This is an alternative approach to https://github.com/duckduckgo/duckduckgo/pull/108 to centralize the renaming and aliasing of country codes to prevent warnings.  It tries to be minimal, allowing IAs to still use Locale::Country functions.
Are we ok with these renames?  I don't know the history behind them but I'm guessing it's so they are readable when displayed.
This needs to go with PRs [#1103](https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1103) and [#1755](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1755) if we decide to move forward with it.
/cc @nilnilnil
> DDG::Meta::CountryCodes - Centralize aliasing/renaming

- .travis.yml
- dist.ini
- lib/DDG/Meta.pm
- lib/DDG/Meta/Data.pm
Note: This needs to be coordinated with internal changes.
DDG::Meta::Data - Mostly provides methods to instant answers so that, when interrogated, they can return metadata about themselves.  However, also includes lookup methods for cases when no IA object is available.
Some changes to dist.ini to allow container builds in travis and automatic Perl deps.
> Add DDG::Meta::Data

- lib/DDG/Meta/Data.pm
Slight change in the logic of when we warn for missing modules.  All missing modules get skipped but we only warn for those that are live.
> DDG::Meta::Data: Only warn if live, but skip all missing mods

- dist.ini
This prevents marking the `DDG::(Goodie|Spice|Fathead|Longtail)Bundle::OpenSourceDuckDuckGo` bundles as dependencies.
/cc @zachthompson
> Autoprereqs ignore DDG::* packages

- .travis.yml
- lib/DDG/Meta/Data.pm
When developing it isn't necessary to have all IA types, e.g. goodie, spice, fathead, and longtail, loaded but only the type being worked on.  This change allows our bundles and their metadata to be conditionally loaded and used in DDG::Meta::Data.
Should help fix [issue #258](https://github.com/duckduckgo/p5-app-duckpan/issues/258), although at least one bundle is still required to be installed.
> Allow conditional loading of IA bundles

- lib/DDG/Meta/Data.pm
The format for adding metadata via javascript to the SERP is the same and done in several places.  This change adds method to return the appropriate javascript string when passed an id.
> Add get_js method to DDG::Meta::Data

- lib/DDG/Meta/Data.pm
Fixes other encoding in the metadata too. 
Before:
After:
@russellholt @zachthompson
> escape chars in metadata

- lib/DDG/Request.pm
Occasionally in a remainder handle users need to know what words trigger the instant answer.  The matched_trigger will provide that.  It also stores the remainder for other uses.
> Add matched_trigger to request

- lib/DDG/Meta.pm
- lib/DDG/Meta/Data.pm
NOTE: Needs to be coordinated with internal.
Abandon adding metadata methods to IAs directly.  We seemingly can't get away from needing to look up metadata after the fact, e.g. via get_ia, and this will simplify the api.  It will also allow us to dynamically update metadata in the future without re-applying keywords.
> Remove apply_keywords from DDG::Meta::Data

- lib/DDG/Meta/Data.pm
When multiple sources have their language set to the same value, we need to return the lowest src_id from fathead_lang.
cc @mrshu
> Use lowest src_id in fathead_lang

- lib/DDG/Meta/Data.pm
The gzip encoded request needs to be tested further.  Commented out.
Check for 304 "Not Modified" in addition to success.
> Revert gzip, check 304 in metadata

- lib/DDG/Meta/Information.pm
- lib/DDG/Rewrite.pm
perl 5.22 throws a warning 'Unescaped left brace in regex is deprecated' if
braces are not escaped in regexes.
> Escape left braces in regexes to fix warnings

- lib/DDG/Meta/Data.pm
Travis has an [issue](https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/90994130#L170) with the s3 cert.  Use the non-ssl endpoint.
> Switch to http for travis

- lib/DDG/Meta/Data.pm
We can disable host verification checks on travis to prevent errors.  Switch back to https everywhere else.
> Switch back to https for s3

- lib/DDG/Meta/Data.pm
HTTPS is proving problematic with S3.  Back to HTTP...forever.  @moollaza you know the drill.
> return to http for metadata

- LICENSE
**Which issues (if any) does this change solve? (please link them here)**
Fixes the content of the LICENSE file. The current LICENSE file just contains the header
meant to be used to license individual files, but should probably contain the Apache 2.0 license body (as with [zeroclickinfo-goodies](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/LICENSE)).
**Briefly describe your fix. Are there any important details we should know about?**
I've replaced the contents of the LICENSE file with the actual Apache 2.0 license body.
**Are you having any problems? Do you need our help with anything?**
Nope.
> Fix LICENSE content (to contain actual license)

- lib/DDG/Meta/ZeroClickInfoSpice.pm
- lib/DDG/Test/Spice.pm
- t/50-spice.t
- t/lib/DDGTest/Spice/AltTo.pm
Currently we need placeholder modules to support alternate end points in spices, e.g. [Dictionary::Pronunciation](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Dictionary/Pronunciation.pm) and friends.  This change allows spices to specify an `alt_to` attribute containing any of the [spice attributes](https://github.com/duckduckgo/duckduckgo/blob/80d6b9469f1ea736df8cff6fc01f87df0b3599e0/lib/DDG/Meta/ZeroClickInfoSpice.pm#L15-L28).  The `alt_to` values are used to:
1.  Generate nginx entries as they did in the past.
2. Are accessible via alt_rewrites for other code, e.g. [duckpan](https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/Web.pm#L62), that needs to dynamically generate these end points.
There are several dependent and/or related …
> Support alt_to attribute in spices

- lib/DDG/Meta/ZeroClickInfoSpice.pm
Continue to evaluate alt_rewrites in get_nginx_conf even if has_rewrite is false.  The [sound cloud](https://github.com/duckduckgo/zeroclickinfo-spice/blob/zach/alt-to/lib/DDG/Spice/SoundCloud.pm#L21) IA is missing a 'spice to' in the parent IA causing the alt_to links to be skipped.
@b2ddg I'll let @moollaza handle this since he's got it all fresh in his head.
> get_nginx_conf depends on alt_rewrites

- lib/DDG/Meta/ZeroClickInfoSpice.pm
- t/50-spice.t
- t/lib/DDGTest/Spice/CallTypeSelf.pm
Encode a query before making a request. Affects spices without the 'spice to' parameter.
Fixes: https://github.com/duckduckgo/duckduckgo/issues/167
@moollaza @bsstoner @zachthompson
> Encode query for spice call

- README.md
The link to documentation should point to the new version of documentation
> Fix stale documentation link in README

- lib/DDG/Rewrite.pm
- t/55-rewrite.t
This change enables SNI for ssl upstreams.  For more info on SNI see:
https://en.wikipedia.org/wiki/Server_Name_Indication
This fixes problems we had with a couple of upstreams such as isitup.org.  Note that I added SNI for all ssl upstreams.  I don't believe this will cause issues for any of the other ssl upstreams.  It works with the github upstream.  
There are 66 ssl upstreams.  I haven't tested them all.  I guess we don't have a way to do that really.  Other than manually.
> Add proxy_ssl_server_name to ssl upstreams.

- lib/DDG/Test/Goodie.pm
@zachthompson We use `Test::Deep` now, so we don't need any of these workarounds.
Also, removing these means people will have to be more specific with things like, say, random tests; instead of just saying `data => '-ANY-'`, they will have to describe the data with (for example) regexes - leading to more comprehensive tests.
We'll need to update any tests that use these.
/cc @mintsoft @moollaza
> Goodie Tests: Remove '-ANY-' and regex tests

- lib/DDG/Meta/ZeroClickInfoSpice.pm
- lib/DDG/Rewrite.pm
- t/55-rewrite.t
This change allows you to define a raw POST body in Spice with a new variable, `post_body`.
This will instruct nginx to `proxy_set_body` to your `post_body` (ideally filled in with captured GET vars) and change the request method to POST.
Cc: @russellholt @MariagraziaAlastra @moollaza @jdorweiler
> Rudimentary POST support for Spice

- CONTRIBUTING.md
**Which issues (if any) does this change solve? (please link them here)**
- The current contributing readme has placeholders for the URL to the issue list and the bad commit example. 
- The links to the style guide and goodies page are non-working. 
- The commit message examples use the past tense, unlike existing commits.
**Briefly describe your fix. Are there any important details we should know about?**
- The link to the issues page now points to https://github.com/duckduckgo/duckduckgo/issues
- The previously invalid link to the style guide now points to https://github.com/duckduckgo/duckduckgo-documentation/blob/master/duckduckhack/resources/code_styleguide.md
- The previously invalid goodies link now points to https://duckduckgo.com/goodies.html/
- The previously invalid metadata.md …
> Fix broken links and placeholders in CONTRIBUTING.md

- lib/DDG/Meta/Data.pm
Add 'get_ias', which allows fetching of multiple IAs that satisfy some lookups joined in an AND condition.
For example, if you wanted to get all the cheat sheets that were live, you could do:
```perl
DDG::Meta::Data::get_ias(
id => sub { $_[0] =~ /_cheat_sheet$/ }, 
production_status => 'live'
);
```
@zachthompson Got any improvements? It seems pretty good speed-wise, though I haven't profiled it...
> Meta::Data - support multi-metadata lookups

- lib/DDG/Meta/CountryCodes.pm
which are in Locale::Codes v3.39.  Should take care of [Tests currently noisy](https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3320).
cc @GuiltyDolphin
> Remove aliases for Russia and Laos

- .travis.yml
- dist.ini
- lib/DDG/Meta/Data.pm
We don't require a Perl module any longer, e.g. fatheads/longtails, even dev for spices/goodies it's ok for it to be blank.
Definitely shouldn't be kicking out IAs without them.
> PM not required

- README.md
Update slack email invite link to self-hosted invite link
Fixes https://github.com/duckduckgo/duckduckgo/issues/227
> README.md: Change slack invite link

- lib/DDG/Rewrite.pm
I noticed several failures in the daily CPAN Testers Reports:
http://www.cpantesters.org/cpan/report/faf9be14-c233-11e6-b6b0-8c67e4596770
The issues is the same as what was addressed in #229, but it looks like one use of keys on a scalar was missed.
> Rewrite.pm: Fix "experimental keys on scalar" error

- lib/DDG/Meta/ZeroClickInfoSpice.pm
- lib/DDG/Rewrite.pm
- t/55-rewrite.t
Reviewer: @marcantonio 
CC: @kablamo @malbin @bsstoner @zachthompson 
Description: This PR adds the ability for a spice to control the NGiNX proxy_{connect,send,read}_timeout variables.
This is in direct response to the issues we've been having with Wordnik. I'm not 100% sure that this will hit the error_page directive (I will be testing that). That will then call the `DDG.spice.failed('some_spice');` when we exceed any of these timeouts. I think it may just work that way now.
> NGiNX generated.conf: Add upstream timeout ability.

- lib/DDG/Meta/ShareDir.pm
Assignee: @zachthompson 
/cc: @mintsoft 
Our `Module::Data` dependency recently switched from using `Path::Class` to `Path::Tiny`. As a result, `$basedir` is now a `Path::Tiny` object, so the `Path::Class`, `subdir` method we call no longer works.
Temporarily we are going to support both `subdir` and `child` to prevent any breakage while upgrading `Module::Data` throughout our code.
Later we will deprecate use of `subdir`.
This manifested in [failing Travis tests](https://travis-ci.org/duckduckgo/zeroclickinfo-goodies/builds/218573065#L6) in the Goodie repo. I recently cleared all the caches (trying to fix something else) and so the modules were forced to update.
1. `cpanm Module::Data`
2. `cd zeroclickinfo-goodies && duckpan test`
3. All tests should fail
1. Install new DDG Bundle
2. `cd …
> ShareDir: Replace Path::Class `subdir` with Path::Tiny `child` method (when available)
